### ISSUE TITLE
`ondevice setup` should create .config/ondevice file if not existing

### ISSUE THREAD

**Issue by Afigene** [ondevice/ondevice-client#19]
When using `ondevice setup` with a new linux-user (someone who didn't set it up before) i get a `FileNotFoundError: [Errno 2] No such file or directory: '/Users/<linux-username>/.config/ondevice`

**Comment by mreithub** [comment]
Hi, thanks for reporting.

The issue seems to be that `ondevice setup` expects `~/.config/` to exists (it creates if it doesn't exist `~/.config/ondevice/`, but not recursively).

I've noticed that before, but thought the chances of it happening out in the wild would be quite low (since many linux commands write their config files to `.config/`, only newly set up machines/users are likely to hit that bug).

For now, I suggest the following workaround (I'll fix the issue in a second, but it might take some time until I publish the next version):

Run the following command as the user that should run `ondevice`:

    mkdir -p ~/.config/


Btw, just outta curiosity: What linux distribution has its home directory in `/Users/.../`? Are you sure you're not on a mac?

**Comment by BrandiATMuhkuh** [comment]
I used a relatively newly setup Mac. I did not check if .config exist for the current user. Since the bug didn't mention that the folder is missing. Only that the file was missing.
